### ISSUE TITLE
How can I pass a browser-sync config along with the webpack config?

### ISSUE THREAD

**Issue by maciossek** [morlay/webpack-browser-sync#1]
Thanks for making this package.

I'd really like to change the default port and switch to https. But am am not sure how to pass browser-sync specific config args.

**Comment by morlay** [comment]
Yep, but the new version of webpack added the [schema](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json) to limited webpack options.

Could we just set browser-sync options to `devServer`?

**Comment by maciossek** [comment]
I am not really sure what you mean. I currently invoke webpack dev server like this:

`node node_modules/webpack-dev-server/bin/webpack-dev-server.js --host 0.0.0.0 --hot --inline --history-api-fallback --progress --colors --port 44311 --https --watch --config webpack/webpack.config.js --DEV --API_URL=https://api.url`

or with your package
`node node_modules/webpack-browser-sync/bin/webpack-browser-sync.js --host 0.0.0.0 --hot --inline --history-api-fallback --progress --colors --port 44311 --https --watch --config webpack/webpack.config.js --DEV --API_URL=https://api.url`

Which starts the webpack-browser-sync with port 3000 without https

**Comment by morlay** [comment]
Too many flags.
may could browser-sync options in webpack options on `devServer.browserSync` https://browsersync.io/docs/options

```js
// webpack.config.js

module.exports = {
   devServer: {
    browserSync: {
     https: true,
   },
  },
}
```
0.4.0 have this feature

**Comment by karneaud** [comment]
when I tried setting 

```
devServer: {
browserSync: {
....
```

I get 

> Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.

browserSync is not in the schema. I'm trying to adjust the host options for browser sync
